"""Modified UserProfile and ContactMessage model with cascade delete

Revision ID: 1572d92330f7
Revises: 9ef522931148
Create Date: 2024-08-29 08:16:54.823676

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1572d92330f7'
down_revision = '9ef522931148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contactmessage_user_profile_id_fkey', 'contactmessage', type_='foreignkey')
    op.create_foreign_key(None, 'contactmessage', 'userprofile', ['user_profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contactmessage', type_='foreignkey')
    op.create_foreign_key('contactmessage_user_profile_id_fkey', 'contactmessage', 'userprofile', ['user_profile_id'], ['id'])
    # ### end Alembic commands ###
