""" added Thumbnail model

Revision ID: 4a93345e588d
Revises: 800d833aa70e
Create Date: 2024-09-18 10:47:15.734901

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4a93345e588d'
down_revision = '800d833aa70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnail',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('uploaded_date', sa.DateTime(), nullable=False),
    sa.Column('thumbnail_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thumbnail')
    # ### end Alembic commands ###
