""" add Author table

Revision ID: 4d0bc1b4e389
Revises: b236c6009c9a
Create Date: 2024-09-03 07:14:15.785745

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4d0bc1b4e389'
down_revision = 'b236c6009c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('expertise', sa.JSON(), nullable=True),
    sa.Column('qualification', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    # ### end Alembic commands ###
