"""rename table signupcreate to userprofile

Revision ID: 536f7435c98a
Revises: 24baade41009
Create Date: 2024-08-23 12:59:13.693758

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '536f7435c98a'
down_revision = '24baade41009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userprofile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')

    )
    op.create_index(op.f('ix_userprofile_email'), 'userprofile', ['email'], unique=True)
    op.drop_index('ix_signupcreate_email', table_name='signupcreate')
    op.drop_table('signupcreate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signupcreate',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='signupcreate_pkey')
    )
    op.create_index('ix_signupcreate_email', 'signupcreate', ['email'], unique=True)
    op.drop_index(op.f('ix_userprofile_email'), table_name='userprofile')
    op.drop_table('userprofile')
    # ### end Alembic commands ###
