""" fixed UserEnrollment relationship

Revision ID: 75427d11c7e2
Revises: ad26be1e49a3
Create Date: 2024-09-19 12:41:51.078462

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '75427d11c7e2'
down_revision = 'ad26be1e49a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
