"""add Contact Message model

Revision ID: 92dfa654bf0a
Revises: b13356090a06
Create Date: 2024-08-23 09:23:42.424498

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '92dfa654bf0a'
down_revision = 'b13356090a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactmessage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contactmessage_email'), 'contactmessage', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contactmessage_email'), table_name='contactmessage')
    op.drop_table('contactmessage')
    # ### end Alembic commands ###
