"""add column firstname to userprofile table

Revision ID: 9ef522931148
Revises: be1397528eee
Create Date: 2024-08-23 13:58:42.321437

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9ef522931148'
down_revision = 'be1397528eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'first_name')
    # ### end Alembic commands ###
