""" modified full_name, email and password in userprofile

Revision ID: adc957fe03c3
Revises: d2408d062a76
Create Date: 2024-10-04 14:32:08.162692

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'adc957fe03c3'
down_revision = 'd2408d062a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
