""" added author column in course table

Revision ID: b236c6009c9a
Revises: ca44a9947367
Create Date: 2024-09-03 05:30:06.025106

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b236c6009c9a'
down_revision = 'ca44a9947367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'author')
    # ### end Alembic commands ###
