"""normalize constctus table

Revision ID: be1397528eee
Revises: 536f7435c98a
Create Date: 2024-08-23 13:24:17.511203

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'be1397528eee'
down_revision = '536f7435c98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contactmessage', sa.Column('user_profile_id', sa.Uuid(), nullable=False))
    op.drop_index('ix_contactmessage_email', table_name='contactmessage')
    op.create_foreign_key(None, 'contactmessage', 'userprofile', ['user_profile_id'], ['id'])
    op.drop_column('contactmessage', 'last_name')
    op.drop_column('contactmessage', 'phone_number')
    op.drop_column('contactmessage', 'email')
    op.drop_column('contactmessage', 'first_name')
    op.add_column('userprofile', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('userprofile', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'phone_number')
    op.drop_column('userprofile', 'last_name')
    op.add_column('contactmessage', sa.Column('first_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('contactmessage', sa.Column('email', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('contactmessage', sa.Column('phone_number', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('contactmessage', sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contactmessage', type_='foreignkey')
    op.create_index('ix_contactmessage_email', 'contactmessage', ['email'], unique=False)
    op.drop_column('contactmessage', 'user_profile_id')
    # ### end Alembic commands ###
