""" add Course table model

Revision ID: ca44a9947367
Revises: 1572d92330f7
Create Date: 2024-09-02 09:09:00.213878

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ca44a9947367'
down_revision = '1572d92330f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('released_date', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('enrollment_count', sa.Integer(), nullable=False),
    sa.Column('certification', sa.Boolean(), nullable=False),
    sa.Column('discount_offers', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('syllabus', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('progress_tracking', sa.Boolean(), nullable=False),
    sa.Column('course_resource', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('faqs', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('accessibility_features', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('course_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('interactive_features', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('video_quality_option', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    # ### end Alembic commands ###
